# Site settings
title: On Food and Coding
email: joe lea public at gmail of the dot com variety
description: > # this means to ignore newlines until "baseurl:"
  A blog on food and coding, apologies for anyone reading who knows nothing about the other
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onfoodandcoding.co.uk" # the base hostname & protocol for your site
twitter_username: joelea
github_username:  joelea

# Build settings
markdown: kramdown
